"""Génération de contrats PDF (WeasyPrint) — miroir de `finance/invoice.py`.

- `build_contract_html()` : gabarit HTML PUR (testable sans WeasyPrint), bilingue
  EN/AR, montants AED chiffres latins.
- `generate_and_store_contract()` : récupère le contrat du tenant (Loi 1), rend le
  PDF, le stocke dans MinIO (contrats/{company}/{ref}.pdf), renvoie l'URL présignée.
Le rendu HTML→PDF réutilise `render_pdf` (import paresseux de WeasyPrint).
"""

from __future__ import annotations

# ruff: noqa: E501  (gabarit HTML/CSS : lignes longues volontaires)
import html
import uuid
from datetime import date
from decimal import Decimal

from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession

from app.core import storage
from app.models.client import Client
from app.models.company import Company
from app.models.property import Property
from app.routers.contracts.service import get_contract
from app.routers.finance.invoice import render_pdf


class ContractPdfError(ValueError):
    """Erreur métier génération contrat (code lisible pour le router)."""

    def __init__(self, code: str) -> None:
        self.code = code
        super().__init__(code)


def _money(value: Decimal | str | float | None) -> str:
    """Format AED, chiffres latins, 2 décimales (tiret si None)."""
    if value is None:
        return "—"
    return f"AED {Decimal(str(value)).quantize(Decimal('0.01')):,}"


def build_contract_html(
    *,
    reference: str,
    company_name: str,
    contract_type: str,
    status: str,
    client_name: str,
    property_label: str,
    amount: Decimal,
    commission_rate: Decimal | None,
    commission_amount: Decimal | None,
    start_date: date | None,
    end_date: date | None,
    signed_date: date | None,
    notes: str | None,
    currency: str = "AED",
) -> str:
    """Construit le HTML d'un contrat (pur, testable)."""
    esc = html.escape

    def row(label: str, value: str) -> str:
        return f'<div class="row"><span class="k">{label}</span><span class="v">{esc(value)}</span></div>'

    dates = []
    if start_date:
        dates.append(row("Start / بداية", start_date.isoformat()))
    if end_date:
        dates.append(row("End / نهاية", end_date.isoformat()))
    if signed_date:
        dates.append(row("Signed / تاريخ التوقيع", signed_date.isoformat()))
    comm = ""
    if commission_rate is not None:
        rate_pct = (commission_rate).quantize(Decimal("0.01"))
        comm = row(f"Commission ({rate_pct}%)", _money(commission_amount))
    notes_block = (
        f'<div class="notes"><div class="k">Notes / ملاحظات</div><p>{esc(notes)}</p></div>'
        if notes
        else ""
    )
    return f"""<!doctype html>
<html><head><meta charset="utf-8"><style>
  @page {{ size: A4; margin: 22mm 18mm; }}
  body {{ font-family: 'Noto Sans', 'Liberation Sans', sans-serif; color: #1a1610; font-size: 12px; }}
  .head {{ display: flex; justify-content: space-between; border-bottom: 2px solid #d4a037; padding-bottom: 12px; }}
  .brand {{ font-size: 20px; font-weight: 700; color: #1a1610; }}
  .title {{ text-align: end; }}
  .title h1 {{ margin: 0; font-size: 22px; color: #d4a037; letter-spacing: 1px; }}
  .muted {{ color: #7a7568; font-size: 11px; }}
  .grid {{ margin-top: 24px; }}
  .row {{ display: flex; justify-content: space-between; padding: 7px 0; border-bottom: 1px solid #e7e2d6; }}
  .k {{ color: #7a7568; }}
  .v {{ font-weight: 600; }}
  .amount {{ margin-top: 22px; border-top: 2px solid #1a1610; padding-top: 10px; display: flex; justify-content: space-between; font-size: 16px; font-weight: 700; }}
  .notes {{ margin-top: 22px; }}
  .notes p {{ color: #3a352c; }}
  .sign {{ margin-top: 48px; display: flex; justify-content: space-between; }}
  .sign .box {{ width: 42%; border-top: 1px solid #1a1610; padding-top: 6px; color: #7a7568; font-size: 11px; }}
  .foot {{ margin-top: 36px; color: #7a7568; font-size: 10px; border-top: 1px solid #e7e2d6; padding-top: 8px; }}
</style></head><body>
  <div class="head">
    <div>
      <div class="brand">{esc(company_name)}</div>
      <div class="muted">Infinity International Facilities Management</div>
    </div>
    <div class="title">
      <h1>CONTRACT</h1>
      <div class="muted">عقد</div>
      <div class="muted">No. {esc(reference)}</div>
      <div class="muted">Type: {esc(contract_type)} · {esc(status)}</div>
    </div>
  </div>

  <div class="grid">
    {row("Client / العميل", client_name)}
    {row("Property / العقار", property_label)}
    {"".join(dates)}
    {comm}
  </div>

  <div class="amount"><span>Amount / المبلغ</span><span>{_money(amount)}</span></div>

  {notes_block}

  <div class="sign">
    <div class="box">Client signature / توقيع العميل</div>
    <div class="box">Agency / الوكالة</div>
  </div>

  <div class="foot">Currency: {esc(currency)} · Generated by SGI — Système de Gestion Immobilière.</div>
</body></html>"""


async def generate_and_store_contract(
    db: AsyncSession, company_id: uuid.UUID, contract_id: uuid.UUID
) -> str:
    """Génère + stocke le PDF d'un contrat du tenant. Retourne une URL présignée.

    Lève ContractPdfError (404 / storage) sinon. Scopé `company_id` (Loi 1)."""
    contract = await get_contract(db, company_id, contract_id)
    if contract is None:
        raise ContractPdfError("contract_not_found")
    if not storage.is_configured():
        raise ContractPdfError("storage_not_configured")

    company = (
        await db.execute(select(Company).where(Company.id == company_id))
    ).scalar_one_or_none()
    client = (
        await db.execute(
            select(Client).where(Client.id == contract.client_id, Client.company_id == company_id)
        )
    ).scalar_one_or_none()
    prop = (
        await db.execute(
            select(Property).where(
                Property.id == contract.property_id, Property.company_id == company_id
            )
        )
    ).scalar_one_or_none()

    client_name = "—"
    if client is not None:
        client_name = (
            (client.company_name or "").strip()
            or " ".join(p for p in [client.first_name, client.last_name] if p).strip()
            or f"#{str(client.id)[:8]}"
        )
    property_label = "—"
    if prop is not None:
        property_label = (
            prop.title_en or prop.title_fr or prop.title_ar or ""
        ).strip() or prop.reference

    contract_html = build_contract_html(
        reference=contract.reference,
        company_name=company.name if company else "Infinity",
        contract_type=contract.type,
        status=contract.status,
        client_name=client_name,
        property_label=property_label,
        amount=contract.amount,
        commission_rate=contract.commission_rate,
        commission_amount=contract.commission_amount,
        start_date=contract.start_date,
        end_date=contract.end_date,
        signed_date=contract.signed_at.date() if contract.signed_at else None,
        notes=contract.notes_en or contract.notes_fr or contract.notes_ar,
    )
    pdf = render_pdf(contract_html)
    object_key = f"contrats/{company_id}/{contract.reference}.pdf"
    await storage.upload_bytes(object_key, pdf, "application/pdf")
    url = await storage.presigned_url(object_key)
    if not url:
        raise ContractPdfError("storage_not_configured")
    return url
