"""Génération du relevé propriétaire en PDF (WeasyPrint) + stockage MinIO.

- `build_statement_html()` : gabarit HTML PUR (testable sans WeasyPrint), bilingue
  EN/AR — lignes Revenu brut / Charges / Commission de gestion / Net à reverser.
- `generate_and_store_statement_pdf()` : récupère le relevé (tenant), rend le PDF
  (réutilise `render_pdf` de finance.invoice), le stocke dans MinIO
  (owner_statements/{company}/{party}/{period}.pdf) et renvoie une URL présignée.

Réutilise la chaîne PDF existante (finance.invoice.render_pdf) — pas de duplication
du moteur WeasyPrint.
"""

from __future__ import annotations

# ruff: noqa: E501  (gabarit HTML/CSS : lignes longues volontaires)
import html
import uuid
from decimal import Decimal

from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession

from app.core import storage
from app.models.company import Company
from app.routers.finance.invoice import render_pdf
from app.routers.owner_statements.service import get_statement, statement_period_label


class StatementError(ValueError):
    """Erreur métier relevé propriétaire (code lisible pour le router)."""

    def __init__(self, code: str) -> None:
        self.code = code
        super().__init__(code)


def _money(value: Decimal | str | float) -> str:
    """Format AED, chiffres latins, 2 décimales."""
    return f"AED {Decimal(str(value)).quantize(Decimal('0.01')):,}"


def build_statement_html(
    *,
    reference: str,
    company_name: str,
    period_label: str,
    owner_name: str,
    gross_revenue: Decimal,
    expenses: Decimal,
    commission: Decimal,
    net_payout: Decimal,
    currency: str = "AED",
) -> str:
    """Construit le HTML d'un relevé propriétaire (pur, testable).

    Net à reverser = brut − charges − commission de gestion (peut être négatif)."""
    esc = html.escape
    return f"""<!doctype html>
<html><head><meta charset="utf-8"><style>
  @page {{ size: A4; margin: 22mm 18mm; }}
  body {{ font-family: 'Noto Sans', 'Liberation Sans', sans-serif; color: #1a1610; font-size: 12px; }}
  .head {{ display: flex; justify-content: space-between; border-bottom: 2px solid #d4a037; padding-bottom: 12px; }}
  .brand {{ font-size: 20px; font-weight: 700; color: #1a1610; }}
  .title {{ text-align: end; }}
  .title h1 {{ margin: 0; font-size: 22px; color: #d4a037; letter-spacing: 1px; }}
  .muted {{ color: #7a7568; font-size: 11px; }}
  table {{ width: 100%; border-collapse: collapse; margin-top: 22px; }}
  th, td {{ padding: 8px 10px; border-bottom: 1px solid #e7e2d6; text-align: start; }}
  th {{ background: #faf7ef; color: #7a7568; text-transform: uppercase; font-size: 10px; }}
  td.num, th.num {{ text-align: end; font-variant-numeric: tabular-nums; }}
  .totals {{ margin-top: 18px; margin-inline-start: auto; width: 50%; }}
  .totals .row {{ display: flex; justify-content: space-between; padding: 5px 0; }}
  .totals .grand {{ border-top: 2px solid #1a1610; font-weight: 700; font-size: 14px; margin-top: 4px; padding-top: 8px; }}
  .foot {{ margin-top: 40px; color: #7a7568; font-size: 10px; border-top: 1px solid #e7e2d6; padding-top: 8px; }}
</style></head><body>
  <div class="head">
    <div>
      <div class="brand">{esc(company_name)}</div>
      <div class="muted">Infinity International Facilities Management</div>
    </div>
    <div class="title">
      <h1>OWNER STATEMENT</h1>
      <div class="muted">كشف حساب المالك</div>
      <div class="muted">No. {esc(reference)}</div>
      <div class="muted">Period / الفترة: {esc(period_label)}</div>
    </div>
  </div>

  <div class="muted" style="margin-top:10px">Owner / المالك: {esc(owner_name)}</div>

  <table>
    <thead><tr>
      <th>Description / الوصف</th>
      <th class="num">Amount</th>
    </tr></thead>
    <tbody>
      <tr><td>Gross rental revenue / إجمالي الإيراد</td><td class="num">{_money(gross_revenue)}</td></tr>
      <tr><td>Expenses &amp; charges / المصروفات</td><td class="num">− {_money(expenses)}</td></tr>
      <tr><td>Management commission / عمولة الإدارة</td><td class="num">− {_money(commission)}</td></tr>
    </tbody>
  </table>

  <div class="totals">
    <div class="row"><span>Gross / الإجمالي</span><span class="num">{_money(gross_revenue)}</span></div>
    <div class="row"><span>Expenses / المصروفات</span><span class="num">− {_money(expenses)}</span></div>
    <div class="row"><span>Commission / العمولة</span><span class="num">− {_money(commission)}</span></div>
    <div class="row grand"><span>Net payout / صافي المستحق</span><span class="num">{_money(net_payout)}</span></div>
  </div>

  <div class="foot">Currency: {esc(currency)} · Generated by SGI — Système de Gestion Immobilière.</div>
</body></html>"""


async def generate_and_store_statement_pdf(
    db: AsyncSession, company_id: uuid.UUID, party_id: uuid.UUID, statement_id: uuid.UUID
) -> str:
    """Génère + stocke le PDF d'un relevé du tenant. Renvoie une URL présignée.

    Lève StatementError (statement_not_found / storage_not_configured)."""
    statement = await get_statement(db, company_id, statement_id)
    if statement is None or statement.owner_party_id != party_id:
        raise StatementError("statement_not_found")
    if not storage.is_configured():
        raise StatementError("storage_not_configured")

    company = (
        await db.execute(select(Company).where(Company.id == company_id))
    ).scalar_one_or_none()
    period_label = statement_period_label(statement.period_year, statement.period_month)
    reference = f"OS-{period_label}-{str(statement.id)[:8]}"

    statement_html = build_statement_html(
        reference=reference,
        company_name=company.name if company else "Infinity",
        period_label=period_label,
        owner_name=str(party_id),
        gross_revenue=statement.gross_revenue_aed,
        expenses=statement.expenses_aed,
        commission=statement.commission_aed,
        net_payout=statement.net_payout_aed,
        currency=statement.currency,
    )
    pdf = render_pdf(statement_html)
    object_key = f"owner_statements/{company_id}/{party_id}/{period_label}.pdf"
    await storage.upload_bytes(object_key, pdf, "application/pdf")
    url = await storage.presigned_url(object_key)
    if not url:
        raise StatementError("storage_not_configured")
    return url
