"""Génération de factures PDF (WeasyPrint) pour les transactions finance.

- `build_invoice_html()` : gabarit HTML PUR (testable sans WeasyPrint), HT/TVA/TTC,
  bilingue EN/AR. Montants AED, chiffres latins.
- `render_pdf()` : HTML → PDF (import PARESSEUX de WeasyPrint pour ne pas exiger
  les libs système — cairo/pango — à l'import du module ; CI sans ces libs OK).
- `generate_and_store_invoice()` : récupère la transaction (type=invoice, tenant),
  rend le PDF, le stocke dans MinIO (factures/{company}/{ref}.pdf), renvoie l'URL.
"""

from __future__ import annotations

# ruff: noqa: E501  (gabarit HTML/CSS : lignes longues volontaires)
import html
import uuid
from datetime import date
from decimal import Decimal

from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession

from app.core import storage
from app.models.company import Company
from app.models.finance import FinanceTransaction


class InvoiceError(ValueError):
    """Erreur métier facture (code lisible pour le router)."""

    def __init__(self, code: str) -> None:
        self.code = code
        super().__init__(code)


def _money(value: Decimal | str | float) -> str:
    """Format AED, chiffres latins, 2 décimales."""
    return f"AED {Decimal(str(value)).quantize(Decimal('0.01')):,}"


def build_invoice_html(
    *,
    reference: str,
    company_name: str,
    issue_date: date,
    description: str,
    amount_ht: Decimal,
    vat_rate: Decimal,
    vat_amount: Decimal,
    currency: str = "AED",
    due_date: date | None = None,
) -> str:
    """Construit le HTML d'une facture (pur, testable). TTC = HT + TVA."""
    ttc = amount_ht + vat_amount
    rate_pct = (vat_rate * 100).quantize(Decimal("0.01"))
    esc = html.escape
    due_row = (
        f'<div class="muted">Due date / تاريخ الاستحقاق: {due_date.isoformat()}</div>'
        if due_date
        else ""
    )
    return f"""<!doctype html>
<html><head><meta charset="utf-8"><style>
  @page {{ size: A4; margin: 22mm 18mm; }}
  body {{ font-family: 'Noto Sans', 'Liberation Sans', sans-serif; color: #1a1610; font-size: 12px; }}
  .head {{ display: flex; justify-content: space-between; border-bottom: 2px solid #d4a037; padding-bottom: 12px; }}
  .brand {{ font-size: 20px; font-weight: 700; color: #1a1610; }}
  .title {{ text-align: end; }}
  .title h1 {{ margin: 0; font-size: 22px; color: #d4a037; letter-spacing: 1px; }}
  .muted {{ color: #7a7568; font-size: 11px; }}
  table {{ width: 100%; border-collapse: collapse; margin-top: 22px; }}
  th, td {{ padding: 8px 10px; border-bottom: 1px solid #e7e2d6; text-align: start; }}
  th {{ background: #faf7ef; color: #7a7568; text-transform: uppercase; font-size: 10px; }}
  td.num, th.num {{ text-align: end; font-variant-numeric: tabular-nums; }}
  .totals {{ margin-top: 18px; margin-inline-start: auto; width: 46%; }}
  .totals .row {{ display: flex; justify-content: space-between; padding: 5px 0; }}
  .totals .grand {{ border-top: 2px solid #1a1610; font-weight: 700; font-size: 14px; margin-top: 4px; padding-top: 8px; }}
  .foot {{ margin-top: 40px; color: #7a7568; font-size: 10px; border-top: 1px solid #e7e2d6; padding-top: 8px; }}
</style></head><body>
  <div class="head">
    <div>
      <div class="brand">{esc(company_name)}</div>
      <div class="muted">Infinity International Facilities Management</div>
    </div>
    <div class="title">
      <h1>INVOICE</h1>
      <div class="muted">فاتورة</div>
      <div class="muted">No. {esc(reference)}</div>
      <div class="muted">Date: {issue_date.isoformat()}</div>
    </div>
  </div>

  {due_row}

  <table>
    <thead><tr>
      <th>Description / الوصف</th>
      <th class="num">Amount excl. VAT</th>
      <th class="num">VAT ({rate_pct}%)</th>
      <th class="num">Total</th>
    </tr></thead>
    <tbody><tr>
      <td>{esc(description or reference)}</td>
      <td class="num">{_money(amount_ht)}</td>
      <td class="num">{_money(vat_amount)}</td>
      <td class="num">{_money(ttc)}</td>
    </tr></tbody>
  </table>

  <div class="totals">
    <div class="row"><span>Subtotal (excl. VAT)</span><span class="num">{_money(amount_ht)}</span></div>
    <div class="row"><span>VAT / ض.ق.م ({rate_pct}%)</span><span class="num">{_money(vat_amount)}</span></div>
    <div class="row grand"><span>Total / الإجمالي</span><span class="num">{_money(ttc)}</span></div>
  </div>

  <div class="foot">Currency: {esc(currency)} · Generated by SGI — Système de Gestion Immobilière.</div>
</body></html>"""


def render_pdf(invoice_html: str) -> bytes:
    """Rend un HTML en PDF. Import PARESSEUX de WeasyPrint (libs système requises
    seulement à l'exécution réelle, pas à l'import du module)."""
    from weasyprint import HTML  # noqa: PLC0415  (import paresseux volontaire)

    return bytes(HTML(string=invoice_html).write_pdf())


async def generate_and_store_invoice(
    db: AsyncSession, company_id: uuid.UUID, txn_id: uuid.UUID
) -> str:
    """Génère + stocke la facture PDF d'une transaction (type=invoice) du tenant.

    Retourne une URL présignée de téléchargement. Lève InvoiceError sinon."""
    txn = (
        await db.execute(
            select(FinanceTransaction).where(
                FinanceTransaction.id == txn_id,
                FinanceTransaction.company_id == company_id,
                FinanceTransaction.deleted_at.is_(None),
            )
        )
    ).scalar_one_or_none()
    if txn is None:
        raise InvoiceError("transaction_not_found")
    if txn.type != "invoice":
        raise InvoiceError("not_an_invoice")
    if not storage.is_configured():
        raise InvoiceError("storage_not_configured")

    company = (
        await db.execute(select(Company).where(Company.id == company_id))
    ).scalar_one_or_none()
    description = txn.description_en or txn.description_fr or txn.description_ar or txn.reference

    invoice_html = build_invoice_html(
        reference=txn.reference,
        company_name=company.name if company else "Infinity",
        issue_date=txn.created_at.date(),
        description=description,
        amount_ht=txn.amount,
        vat_rate=txn.vat_rate,
        vat_amount=txn.vat_amount,
        currency=txn.currency,
        due_date=txn.due_date,
    )
    pdf = render_pdf(invoice_html)
    object_key = f"factures/{company_id}/{txn.reference}.pdf"
    await storage.upload_bytes(object_key, pdf, "application/pdf")
    url = await storage.presigned_url(object_key)
    if not url:
        raise InvoiceError("storage_not_configured")
    return url
